# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          command: npm install --global yarn
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
orbs:
  node: circleci/node@5.0.2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build