# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
      - setup_remote_docker:
          version: 20.10.14
orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@2.2.0
