# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    steps:
      - run:
          sudo apt-get install -y docker
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
orbs:
  node: circleci/node@4.7.0
workflows:
  version: 2
  build_and_test:
    jobs:
      - build