# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: cimg/base:2023.02 
      - image: redis
    resource_class: small
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          command: yarn install
      - run:
          command: yarn test:ci
workflows:
  version: 2
  build_and_test:
    jobs:
      - build